global:
  env: local

log:
  level: info
  format: text
  service_name: auth-proxy

servers:
  client:
    addr: localhost:38081

jwt:
  secret: local-dev-secret-change-in-prod
  access_token_ttl_seconds: 900
  refresh_token_ttl_seconds: 604800
