global:
  env: prod

log:
  level: info
  format: json
  service_name: main-service

servers:
  client:
    addr: 0.0.0.0:8080
  metrics:
    addr: 0.0.0.0:9100

database:
  dsn: ${DATABASE_DSN}
  auto_migrate: true

jwt:
  secret: ${JWT_SECRET}
  access_token_ttl_seconds: 900
  refresh_token_ttl_seconds: 604800

chat:
  message_ttl_seconds: 60

cors:
  allowed_origins:
    - https://beepru.ru
